# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Y7qVtQIMQJ3cNTUvPyd440Bv6DW0-Vp
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("arjunbhasin2013/ccdata")

print("Path to dataset files:", path)

import pandas as pd
import os


file_path = os.path.join(path, "CC GENERAL.csv")

df = pd.read_csv(file_path)
print("Data loaded successfully!")
print("Shape:", df.shape)
df.head()

# статистика
df.info()
df.isna().sum()
df.describe().T

# CUST_ID не влияет на поведение клиента
df = df.drop('CUST_ID', axis=1)

df = df.fillna(df.median())

df.isna().sum().sum()
# so there is no NaN value

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

inertia = []
silhouette = []

K = range(2, 11)  # от 2 до 10 кластеров
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df_scaled)
    inertia.append(kmeans.inertia_)
    silhouette.append(silhouette_score(df_scaled, kmeans.labels_))

# Визуализируем
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(K, inertia, '-o')
plt.title('Метод локтя')
plt.xlabel('Количество кластеров (k)')
plt.ylabel('Inertia')

plt.subplot(1,2,2)
plt.plot(K, silhouette, '-o', color='orange')
plt.title('Коэффициент силуэта')
plt.xlabel('Количество кластеров (k)')
plt.ylabel('Silhouette Score')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=20)
kmeans.fit(df_scaled)
labels = kmeans.labels_
df['Cluster'] = labels
df.head()

cluster_profile = df.groupby('Cluster').mean().T
cluster_profile

import seaborn as sns

plt.figure(figsize=(10, 6))
sns.heatmap(cluster_profile, cmap='coolwarm')
plt.title('Средние значения признаков по кластерам')
plt.show()

"""
##Cluster 0 — «Пассивные клиенты с низкой активностью»

balance, cash advice низкий, purchaceses and credit limit небольшие что означает клиенты редко использует карту и очень мало совершают покупок.

## Cluster 1 — «Активные клиенты с высоким кредитным лимитом»
credit limit самый выскоий purchaceses and payments высокие balance умеренный что означает клиенты активно пользуються кредтиом, совершают крупные покупки, платят вовремя.

## Cluster 2 — «Клиенты с высоким лимитом, но низкой активностью»
credit limit самый выскоий, purchases and cash advance низкий payments средний что означает у клиентов есть возможность тратить, но они почти не пользуются картой. Возможно, используют её как резерв.

## Cluster 3 — «Клиенты с частыми авансами наличными»
cash advance and cash advance trx повышенные, purchases низкие, credit limit средний что означает клиенты, которые часто используют кредитку для снятия наличных — возможно, из-за финансовых трудностей.
"""

import joblib

joblib.dump(kmeans, 'kmeans_model.joblib')
joblib.dump(scaler, 'scaler.joblib')

print("Модель и скейлер успешно сохранены!")
cluster_profile.to_csv('cluster_profiles.csv')